export const ASSET_TYPES = [
  "WATER_PIPE",
  "WASTEWATER_PIPE",
  "DRAINAGE_PIPE",
  "MANHOLE",
  "VALVE",
  "PRV",
  "PUMP_STATION",
  "PUMP",
  "WWTP",
  "RETENTION_POND",
  "CANAL",
  "ROAD",
  "BRIDGE",
  "SENSOR_NODE"
] as const;

export const ASSET_STATUSES = ["NORMAL", "WATCH", "WARNING", "CRITICAL", "OUT_OF_SERVICE"] as const;
export const SENSOR_TYPES = [
  "FLOW",
  "PRESSURE",
  "WATER_LEVEL",
  "RAINFALL",
  "WATER_QUALITY_COD",
  "WATER_QUALITY_BOD",
  "WATER_QUALITY_PH",
  "PUMP_VIBRATION",
  "PUMP_ENERGY",
  "GATE_POSITION"
] as const;
export const READING_QUALITIES = ["GOOD", "SUSPECT", "BAD"] as const;
export const INCIDENT_TYPES = [
  "LEAKAGE",
  "PIPE_BURST",
  "BLOCKAGE",
  "FLOODING",
  "PUMP_FAILURE",
  "ODOR_COMPLAINT",
  "WATER_QUALITY_EXCEEDANCE",
  "ROAD_SETTLEMENT",
  "MANHOLE_OVERFLOW"
] as const;
export const INCIDENT_STATUSES = ["OPEN", "INVESTIGATING", "RESOLVED", "CLOSED"] as const;
export const PLAN_OBJECTIVES = ["MINIMIZE_RISK", "REDUCE_LEAKAGE", "FLOOD_PREVENTION", "NRW_REDUCTION", "WASTEWATER_COMPLIANCE", "BALANCED"] as const;
export const ACTION_TYPES = ["INSPECT", "CCTV_INSPECTION", "CLEANING", "REPAIR", "REPLACE", "REHABILITATE", "SENSOR_INSTALL", "HYDRAULIC_CALIBRATION"] as const;
export const WORK_PRIORITIES = ["LOW", "MEDIUM", "HIGH", "URGENT"] as const;
export const WORK_ORDER_STATUSES = ["BACKLOG", "ASSIGNED", "IN_PROGRESS", "DONE", "CANCELLED"] as const;
export const SCENARIO_TYPES = ["HEAVY_RAIN", "PUMP_FAILURE", "PIPE_LEAKAGE", "PIPE_BLOCKAGE", "WASTEWATER_OVERLOAD", "COMBINED_STRESS"] as const;

export type AssetTypeValue = (typeof ASSET_TYPES)[number];
